GET http://localhost:5000/all-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWJkdXIgUmFobWFuIiwiZW1haWwiOiJyai5hYmR1cnJhaG1hbkBnbWFpbC5jb20iLCJwaG9uZSI6IjAxNzU3MTEwMjk2IiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE2NDA2MjM4NDB9.4O1XPNoSNcL5djHFzR9CQlwGw1v-UXESIONQYXqzDqc